---
title: ego and action
date: 2025-12-26 17:57:31
layout: post
lang: en
tags: []
draft: false
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: en

Our Ego fights action with smart questions and doubts, and if you engage in those, you fell into the trap, it’s an endless cycle from others — more questions, doubts — right and wrong, and no progress. 

If you fell into ego’s trap, you’re dreaming, and dreams are way to live in results, external outcome focused (validation and reaction of others). It is a no creativity zone, as the dreams are built on conditioning of thoughts, which can only be from the past — it takes you away from the present & the friction with an idea you’re dealing with, a negative barrier to action, as it pretends to you feel how it’d be once you’re there

Attend to the present, giving attention to it, and that’ll lead to the right understanding and action; effortlessly. When the clouds are clear, you can see the sun; otherwise, you’ll only see all the shapes of the cloud and assume that’s real.
