---
title: on knowing more
date: 2026-01-05 07:01:24
layout: post
lang: en
tags: []
draft: false
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: en

There is a notion we all carry in society, which is the more you know, in life, in any subject, the better you are - not just an academic, but perhaps also a better human being. In fact, it is often shared as a gospel truth to younger people.

We see it all around us, look at kids memorising tables, “book lovers” taking pride in reading and buying certain number of books in a year, dad’s reading the newspaper and watching news religiously, younger crowd referencing popular celebrities in conversations.

If you’re wondering what is the problem with this, there is a subtle nuance i want to highlight, and perhaps if you can observe how this drives your own consumption patterns, you’ll be able to appreciate it.

Knowing more, is not the same as understanding more, you could know a ton, be an academic or pundit in a field, but still have zero understanding of any of it - now what will you do when you’ve attached yourselves with the identity of a knower? 

You’ll be constantly paranoid in your own world, seeking more information to solve any problem, because your assumption is there is always more to know, you’ll be constantly seeking - of course, because you don’t understand it, and there is infinite amount of information. In fact you can feel smart picking anything up randomly, and looking at it with your problems lens - you  feel wise to see an insight in it. This all gets reflected in how you speak to others - now that you’ve put so much effort into this process, you shame others if others don’t know what we know. All of it is a useless gymnastic of thinking, poor thinking. 

It is because you don’t understand the situation, or the information - now what the heck is understanding? understanding as i understand, is looking at things from unbiased perspective, giving it all your attention by being with it.

If you ask, how is it different from what we already do? What we already do is consume information, even when “mindfully” done, we’re not able to look at it clearly due to the goal we’re seeking, so the information becomes “the tool”, and what do we do with a tool when we’ve a problem? We hit it everywhere thinking it’s the solution.

I shall write more on this, which will make this clear to both of us.