---
title: relationship with the ghost
date: 2026-01-06 21:03:38
layout: post
lang: en
tags: []
draft: false
---
#+OPTIONS: toc:nil num:nil
#+LANGUAGE: en


If we observe our closest relationships, we will find, we make of them what we want, we look at parts we have interest in. It is almost like a toy in a child's hand, they do what you want to with it, fly the car or break it open, without attempting to understand the toy's true nature.

Most relationships are transactions of desires, we look at the other person with the filter of our own desire, and the other does the same. It is a relationship of comfortable utility.

You see, when we meet people, our minds, are quick to create images, and fit people in frames, in traditional sense, the depth of a relationship is defined by how vivid the image is.

But, do we realise what are images? Images come from the past, representation of a dead person. I'd argue, is it really a relationship at that point, or an animal put in a cage for the masters entertainment? 

If we observe our self when we talk to them, aren’t we coming with a bag of beliefs about them? In that case, can we really appreciate them for WHO they are? 

If we've to see people for who they are, at any moment, we need to avoid being full of ourselves - our beliefs and thoughts. We cannot see someone for who they are, and appreciate their existence, if we're full of ourselves. Maybe that is why loving takes effort, I'm not talking about the loving of the animal biology attraction kind, but of independence and freedom, one that sets free.
